#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_MAINDLG                             100
#define IDD_SETDLG                              101
#define IDD_ICONDLG                             102
#define IDD_SETTDLG                             103
#define IDR_POPUP                               300
#define ID_TOOLB                                600
#define IDB_LOGO                                602
#define IDC_GRP2                                1000
#define IDC_FILELIST                            1001
#define IDC_PRBAR                               1004
#define IDC_STBAR                               1005
#define IDC_EXTROPT                             1006
#define IDC_FATTOPT                             1007
#define IDC_MSCOPT                              1008
#define IDC_1                                   1009
#define IDC_2                                   1010
#define IDC_3                                   1011
#define IDC_4                                   1012
#define IDC_5                                   1013
#define IDC_CUSTDIR                             1014
#define IDC_SAVEBUT                             2005
#define IDC_JCANCEL                             2009
#define IDC_TRAY                                2011
#define IDC_SHELL                               2012
#define IDC_GRP4	                            2013
#define IDC_OUTFILE                             2014
#define IDC_GUIUNP                              3001
#define IDC_FILENAMES                           3002
#define IDM_ADDFILE                             3002
#define IDC_CRC                                 3003
#define IDM_REMFILE                             3003
#define IDC_CRYPT                               3004
#define IDC_PACK                                3005
#define IDM_CLRFILE                             3005
#define IDC_SELFREM                             3006
#define IDM_ADDFOLDER                           3006
#define IDC_SAVE                                3007
#define IDM_                                    3007
#define IDC_CANCEL                              3008
#define IDM_RENAME                              3008
#define IDC_GRP1                                3009
#define IDC_ICONPIC                             3010
#define IDC_ICONBUT                             3011
#define IDC_LST1                                5001
#define IDC_STC1                                5002
#define IDC_ICONOK                              5003
#define IDC_ICONCNL                             5004
#define IDC_LOGO                                5004
